#!/bin/bash

[ ! -d "build/" ] && mkdir build

cd build || exit 0

# WIP
cmake .. \
	-DENABLE_DOXYGEN=OFF \
	-DLICENSE_GPL_SHOGUN=OFF \
	-DUSE_SVMLIGHT=OFF \
	-DBUILD_META_EXAMPLES=OFF \
	-DUSE_LZO=OFF \
	-DVIENNACL_WITH_OPENCL=OFF \
	-DENABLE_LZO=OFF \
	-DENABLE_BZIP2=OFF \
	-DENABLE_TESTING=OFF \
	-DLIBSHOGUN_BUILD_STATIC=ON \
	-DBUILD_STATIC=ON \
	-DENABLE_HDF5=OFF \
	-DENABLE_ZLIB=OFF \
	-DCMAKE_INSTALL_PREFIX=$(pwd)/bins &&
	make
