#!/bin/bash

mkdir build && cd build

# WIP
cmake .. -DENABLE_DOXYGEN=OFF -DLICENSE_GPL_SHOGUN=OFF -DUSE_SVMLIGHT=OFF -DBUILD_META_EXAMPLES=OFF -DUSE_LZO=OFF -DVIENNACL_WITH_OPENCL=OFF -DENABLE_LZO=OFF -DENABLE_BZIP2=OFF -DLIBSHOGUN_BUILD_STATIC=ON -DENABLE_HDF5=OFF -DENABLE_ZLIB=OFF \
	&& make
